### ISSUE TITLE
Wrong node coloring.

### ISSUE THREAD

**Issue by ps-pat** [JuliaPlots/GraphRecipes.jl#163] opened 2021-08-03 18:47 UTC
The nodes coloring is wrong for some graphs. For instance,
```julia
using GraphRecipes
using Plots

g = [0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0;
     0 0 0 0 0 0 0 0 0;
     0 0 1 0 1 0 0 0 0;
     1 1 0 0 0 0 0 0 0;
     0 0 0 1 0 1 0 0 0;
     0 0 0 0 0 0 1 1 0]

colors = [:blue,
          :red,
          :blue,
          :red,
          :red,
          :blue,
          :blue,
          :blue,
          :blue]

graphplot(g, names = 1:9, nodecolor = colors)
```
produces the following plot:
![gr](https://user-images.githubusercontent.com/4511907/128069423-91e2d34f-baef-4073-b4c7-4ab1ab431e03.png)

However, from my understanding, only nodes 2, 4 and 5 should be colored red.

**Comment by mroavi** [comment] 2021-08-05 15:13
Duplicate of #153. Would be nice to know from the repo maintainers if there is any plan to work on this, or if, on the other hand, would be better to move to another solution like [GraphMakie](https://github.com/JuliaPlots/GraphMakie.jl).

**Comment by BeastyBlacksmith** [comment] 2022-01-20 20:17
My understanding of this issue is the following: `nodecolor` is a 9-element vector, `graphplot` creates 18 series: 8 edges, 9 nodes, and one for the labels ( in that order ).
`fillcolor` will get cycled to match 18 series and since the nodes start 1 off, since its 8 edges before, you get the shift of colors

**Closed** 2022-01-22 18:44 UTC
Labels: GraphRecipes
